# Generated by Django 6.0.1 on 2026-01-14 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
        ('directors', '0001_initial'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('release_year', models.IntegerField(db_index=True)),
                ('release_date', models.DateField()),
                ('duration_minutes', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('budget', models.BigIntegerField(blank=True, null=True)),
                ('box_office', models.BigIntegerField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='directors.director')),
            ],
            options={
                'db_table': 'movies',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(blank=True, max_length=255)),
                ('cast_order', models.IntegerField(default=0)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
            options={
                'db_table': 'movie_cast',
                'ordering': ['cast_order'],
                'unique_together': {('movie', 'actor')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(related_name='movies', through='movies.MovieCast', to='actors.actor'),
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genres.genre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
            options={
                'db_table': 'movie_genres',
                'unique_together': {('movie', 'genre')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies', through='movies.MovieGenre', to='genres.genre'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title'], name='movies_title_179e04_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['release_year'], name='movies_release_d7b230_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-release_date'], name='movies_release_c93b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['director'], name='movies_directo_b187f9_idx'),
        ),
    ]
